export const categories = {
  salary: "Salario",
  investmentIncome: "Ingresos por Inversiones",
  pensions: "Pensiones",
  rentals: "Alquileres",
  occasionalIncome: "Ingresos Eventuales",
  housing: "Vivienda",
  utilities: "Servicios Básicos",
  food: "Alimentación",
  transportation: "Transporte",
  health: "Salud",
  entertainment: "Entretenimiento",
  clothing: "Ropa",
  education: "Educación",
  savingsAndInvestments: "Ahorros e Inversiones",
  debts: "Deudas",
  others: "Otros",
};
